name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: RÃ©cupÃ©rer le code
        uses: actions/checkout@v4

      - name: Installer lâ€™environnement Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Installer les dÃ©pendances
        run: cargo fetch

      - name: Lancer la vÃ©rification (build)
        run: cargo build --verbose

      - name: Lancer les tests unitaires
        run: cargo test --verbose

      - name: Envoyer notification Discord (succÃ¨s)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"âœ… Workflow **${{ github.workflow }}** rÃ©ussi !\nğŸ”¹ Branche: ${{ github.ref_name }}\nğŸ‘¤ Auteur: ${{ github.actor }}\nğŸ”— Lien: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}


      - name: Envoyer notification Discord (Ã©chec)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"âŒ Workflow **${{ github.workflow }}** Ã©chouÃ© !\nğŸ”¹ Branche: ${{ github.ref_name }}\nğŸ‘¤ Auteur: ${{ github.actor }}\nğŸ”— Lien: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
